### ISSUE TITLE
Make back tick key optional

### ISSUE THREAD

**Issue by johnathanludwig** [BriteSnow/vscode-toggle-quotes#1]
Could you add a config option to exclude the back tick (`) from the characters this plugin rotates through?

I mostly use ruby and the back tick is not a character you use with strings.

**Comment by jeremychone** [comment]
@johnathanludwig Yes, make sense. Give me few days.

**Comment by jeremychone** [comment]
This will be implemented in #2. So, tick only js, ts, and md by default, you can customize the sequence per language with `togglequotes.chars`. See #2.
