### ISSUE TITLE
Unknown editor configuration setting "togglequotes.chars"

### ISSUE THREAD

**Issue by doug-numetric** [BriteSnow/vscode-toggle-quotes#10]
vscode complains with warning "Unknown editor configuration settings" at the squiggly underline in the screenshot.

![image](https://user-images.githubusercontent.com/28833430/45565657-65ff8700-b811-11e8-91e1-3e1dbb2f8eb4.png)

**Comment by jeremychone** [comment]
@doug-numetric Yes, I do not think there is a way to extends a "per language" custom property. I looked at it. 

If you know otherwise, let me know or do a pull request, happy to fix this warning.

**Comment by enriquein** [comment]
Does this mean then that the feature of having custom per-language settings doesn't work? If yes, would you be open to a pull request implementing handling this kind of configuration as configuration settings for the extension?

I'm trying to configure Pug files to work exactly as javascript files but I can't figure out how to make it work.

**Comment by ERROPiX** [comment]
Same for me,
![image](https://user-images.githubusercontent.com/6576868/98865824-448b9b80-246c-11eb-8525-cb23a942798b.png)

**Comment by ERROPiX** [comment]
Also, adding the settings given in the description is not working, vs code show it as "Unknown Configuration Setting"

![image](https://user-images.githubusercontent.com/6576868/98866794-c5976280-246d-11eb-83f8-897ec71a8b58.png)

**Comment by bbugh** [comment]
Even though it gives the warning shown in the top comment, it still works. I was able to add \` to togglequotes for Vue files.
