### ISSUE TITLE
Allow include backticks in default quote characters for *.vue files, but only inside <script> tags

### ISSUE THREAD

**Issue by salvadornico** [BriteSnow/vscode-toggle-quotes#11]
This change seems simple enough to implement across the entire file, but I was wondering if someone could help with limiting the change to only inside the `<script>` tags of the file?

**Comment by jeremychone** [comment]
Can you give me an example, not sure I fully get the use case. 

Also, not sure it is a good idea to put too much content specific in this logic, but anyway, I would be interested to better understand the usecase.

**Comment by salvadornico** [comment]
With *.vue files, there are three sections you can have: the template, script, and style, each opened and closed like in HTML:

```
<template>
    <!-- HTML goes here -->
</template>

<script>
    // Javascript goes here
</script>

<style>
    // CSS goes here
</script>
```

I was hoping to add the backticks as an option for toggling, but only while inside the `<script>` tags, which is where you would write your JS/TS code. Everywhere else, the backticks wouldn't be valid syntax.

**Comment by jeremychone** [comment]
@salvadornico Right now the plugins follows the context sent by VSCode and I am not sure I want to be smarter than that. Would be clunky, might have some unwanted side effect.

**Comment by unclejustin** [comment]
I disagree with the premise of this issue. It is common enough to embed javascript in the html section of a vue SFC so having the ability for backticks there makes sense.

**Comment by hooray** [comment]
seconded, I need this feature

**Comment by jeremychone** [comment]
Right now, this plugin follows the language context sent by VSCode. Trying to understand file-specific context outside of VSCode context would be quite a task and might have some unwanted effect. I respect other perspectives, but for now, this is out of the scope of this plugin.

**Comment by jeremychone** [comment]
Btw, I am planning to merge #41 which will add backtick to vscode vue.js context.
