### ISSUE TITLE
Extension broken with latest version of vscode

### ISSUE THREAD

**Issue by marcofugaro** [BriteSnow/vscode-toggle-quotes#14]
Hi, I've just installed the extension, but when i run the `Toggle Quotes` command or press the shortcut nothing happens. I've tried multiple ways and still nothing happens when I run it.

Is there an issue with the latest version? Could you check? Thanks

**Comment by jeremychone** [comment]
@marcofugaro Good timing, just updated my machine and I had to do a fresh install. Worked as before. `cmd + "` will toggle through the quotes.

**Comment by marcofugaro** [comment]
Sorry, it was a problem with vscode not recognizing the `'` on my italian keyboard, changed the shortcut and the problem di not occour.

**Comment by giorgiobeggiorasoprasteria** [comment]
> Sorry, it was a problem with vscode not recognizing the `'` on my italian keyboard, changed the shortcut and the problem di not occour.

did you find the ' equivalent character for Italian keyboards?

**Comment by jeremychone** [comment]
@marcofugaro thanks for the update. Really appreciate.
