### ISSUE TITLE
Add icon to project

### ISSUE THREAD

**Issue by BBlackwo** [BriteSnow/vscode-toggle-quotes#17]
Would be nice to have an icon for the extension. Makes it easier to find in the extensions menu. Currently, it looks like this:

<img width="327" alt="Screen Shot 2019-07-24 at 9 42 30 am" src="https://user-images.githubusercontent.com/7598058/61754651-697f7980-adf7-11e9-9836-f9316a7f0b4d.png">

Just need to add an `icon` field in the package.json. See the [Extension Manifest](https://code.visualstudio.com/api/references/extension-manifest#fields) docs.
>The path to the icon of at least 128x128 pixels (256x256 for Retina screens).

**Comment by jeremychone** [comment]
yes, good one. I will try to make one when I have time.

**Comment by will-stone** [comment]
Hi. Firstly, thanks for this project, I use it all the time.

How about a simple logo?

<img src="https://user-images.githubusercontent.com/654103/84200578-f4fd0a00-aa9e-11ea-9c18-978f47c40685.png" alt="logo" width="100" height="100" />

Something that's instantly recognisable. Happy to iterate/PR if you like?

**Comment by jeremychone** [comment]
@will-stone Thanks, love it. Feel free to do the PR. Happy to update.

**Comment by jeremychone** [comment]
the merge was applied in Jun 10 2020
