### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by ERROPiX** [BriteSnow/vscode-toggle-quotes#29]
I have tried much time to toggle quotes in the selected string and it did nothing, I tried in JS and PHP files.

**Comment by jeremychone** [comment]
yes, working for me daily and many other I think. 

A while back someone had issues with the key mapping with some foreign keyboard and then they found the solution (do not remember where)

**Comment by ERROPiX** [comment]
It is not working for me, I even tried running the command from the commands popup and got no results.

**Comment by jeremychone** [comment]
I will try to look at it, but I probably use it 10 to 50 times a day, and always working. 

What is your OS / VSCode language / keyboard config?

**Comment by ERROPiX** [comment]
I am using on Windows 10 English System and keyboard language.
Hotkeys shouldn't be a problem, as executing the command directly doesn't work.

Maybe I am using it wrong since there are no instructions on how to use it.

**Comment by jeremychone** [comment]
![image](https://user-images.githubusercontent.com/74671/98864389-a8877300-241e-11eb-9b72-e9fea671ab35.png)


Perhaps you select what you want to toggle. It's the other way around, you put your cursor in the quote pair you want to toggle. This allows to "exclude" was you do not want to count.

**Comment by ERROPiX** [comment]
> you put your cursor in the quote pair you want to toggle

This was the most needed instruction, I was selecting the whole string, then I tried selecting the quotes, but nothing worked.
When I put the cursor between the two quotes, it worked fine.

Please add a better description for this great addon 👍

**Comment by jeremychone** [comment]
Very good point. I need to do a little animated gif, that shows how it works. 

There is a reason for this behavior, because, this way, the logic does not have to be too complex and the human can give the necessary hint. 

But good point, about the documentation deficiency. Will fix it in the next coming days.

**Comment by jeremychone** [comment]
Closing, see #30.
