### ISSUE TITLE
Support multi character beginning/end strings, e.g. Ruby's Percent Strings, here docs etc.

### ISSUE THREAD

**Issue by bb** [BriteSnow/vscode-toggle-quotes#38]
I used the following config trying to get support for [Ruby's Percent Strings](https://docs.ruby-lang.org/en/3.0.0/doc/syntax/literals_rdoc.html#label-Percent+Strings):

```json
  "[ruby]": {
    "togglequotes.chars": [
    "\"",
    "'",
    ["%(", ")"]
  ]
  },
```

While it worked great to switch from `"foo"` to `'foo'` to `%(foo)`, after that last one it won't cycle back to the first.

I also experimented with an extended version which shows that it just stops as soon as the beginning is a two or three character string.
```json
  "[ruby]": {
    "togglequotes.chars": [  
    "\"",
    "'",
    "`",
    ["%(", ")"],
    ["%[", "]"],
    ["%{", "}"],
    ["%q(", ")"],
    ["%i(", ")"],
    ["%r(", ")"],
    ["%s(", ")"],
    ["%w(", ")"],
    ["%x(", ")"],
  ]
  },
```

I think it would be great to support multi-character pairs.

Going beyond that, here are some more ideas which might be extracted to separate issues if somebody is interested:

### Extended version for here docs

As an extended version, maybe even including newlines to allow [here docs](https://en.wikipedia.org/wiki/Here_document) like e.g.

```ruby
puts <<EOF
foo
bar
EOF
```

However, I personally use different here doc markers and not only EOF, so this might become a rabbit hole. Also there are extra variants for not having the end marker at the beginning of the line (like `<<~EOF`). Also, this would possibly raise additional questions like indentation etc.

### Basic and advanced replacements

As pointed out in the previous examples, there might be tons of possible replacements one might add, but 90% of the time, it's only `"`, `'` and `` ` ``. A solution might be a second command, e.g. with additional alt-modifier by default. It could be configured with `"togglequotes.extChars"` and cycle not only through `"togglequotes.chars"` but both lists. The existing command could replace from both, but only to the regular list.

I'll stop here as this is most likely already waaaay out of scope for this nice little extension 😉

**Comment by jeremychone** [comment]
First good bug reporting. For the other ideas, might be other tickets as you mention. There is a current pull request being discussed about escape chars and all. Will come back with more thought. I need to look at the bug to see if this can be fixed.

**Comment by jeremychone** [comment]
Closing, see #37 for context.
