### ISSUE TITLE
Wrong default keybinding on nordic keyboard layout :bug:

### ISSUE THREAD

**Issue by Vennufius** [BriteSnow/vscode-toggle-quotes#49]
I have a Nordic keyboard layout (Finnish in my case) and for me the default key binding was set to `ctrl + ä` instead of `ctrl + '`. Not really too big of an issue, but a slight inconvenience. Took me a while to figure out why it wasn't working.

**Comment by jeremychone** [comment]
What should be the fix for that? Did you remap it?

**Comment by Vennufius** [comment]
@jeremychone  I just changed the key binding in VSCode. If the root cause is not found, maybe a mention in the instructions would be enough. Not sure if this was just a me problem or if other people have encountered this error as well. Just wanted to mention this if other people come across the same issue. Now that I got it working, this extension is a life saver, kudos to you my friend🙏

**Comment by jeremychone** [comment]
Hi @Redsandro, I've merged your README PR, thank you so much. I'm closing this since I've merged the PR, but feel free to let me know if there's anything else we could do.
