### ISSUE TITLE
The 'Toggle Quotes' extension is not available in Visual Studio Code for the Web.

### ISSUE THREAD

**Issue by bcowgill** [BriteSnow/vscode-toggle-quotes#50]
Wanted to install Toggle Quotes into the in browser editor https://vscode.dev  But get the error:

The 'Toggle Quotes' extension is not available in Visual Studio Code for the Web. Learn Why

Learn Why link takes to:
https://code.visualstudio.com/docs/editor/vscode-web#_extensions

Can you provide partial or full support for the in browser editor?

This is the most useful feature that vscode for web is missing out of the box.

**Comment by jeremychone** [comment]
Ho, interesting. I will try to find time to look at it.
