### ISSUE TITLE
Editor configuration setting unknown

### ISSUE THREAD

**Issue by midgethoen** [BriteSnow/vscode-toggle-quotes#6]
First off; awesome plugin 💪 

minor issue im having:

vscode doesn't know about the configuration described in the README, which makes me unable to use autocomplete for configuring this

<img width="473" alt="schermafbeelding 2018-03-21 om 15 17 27" src="https://user-images.githubusercontent.com/4599476/37714917-fd66edf4-2d1a-11e8-9615-4fc73e3ce5d5.png">

not sure what's going on, I though vscode would be smart about this.

does anybody else have this problem?

**Comment by jeremychone** [comment]
yes, this seems to be a limitation of vscode. In fact, vscode does not really support property cascading from language scope and I had to find a way to support it. The catch is that we get those warnings. 

If it is fine with you, I will close this ticket since there are not much we can do for now.

**Comment by midgethoen** [comment]
> In fact, vscode does not really support property cascading from language scope and I had to find a way to support it

that's a pity. Hopefully it will get fixed some day.

thanks for your time.
