### ISSUE TITLE
Toggle quotes not working

### ISSUE THREAD

**Issue by Perkin5** [BriteSnow/vscode-toggle-quotes#60]
I'm using Windows 11. When I try the shortcut ctrl+', all it does is open the terminal. I tried 'ctrl shift P' and 'toggle quotes' appeared but nothing happened to my selection.
What's happening?

**Comment by jeremychone** [comment]
Hum, I am not sure. Here are some tips.

- Quote pairs will be detected in both directions from the cursor.
- If no pair is found, it will cancel and do nothing.
- To bypass some text with potential quotes, just select it, then the start and end of the section become the new boundaries.

**Comment by Perkin5** [comment]
Sadly I have to say I am abandoning Vscode. About half the extensions don't work and many of the shortcuts are erratic in their operation. I could make a list of at least 20 things that I find intensely frustrating. I'm off back to Sublime Text!

**Comment by jeremychone** [comment]
Sorry to hear that. There is a new upcoming Zed as well, which might be interesting.
