### ISSUE TITLE
Default hotkey is win+' on Windows

### ISSUE THREAD

**Issue by evaera** [BriteSnow/vscode-toggle-quotes#7]
Feels strange having the default hotkey involving the Windows button on Windows. I've rebound it to `ctrl+'`, but would be nice for new users of the extension to skip that step.

In the keybindings contribution, `cmd` is perceived as the Windows button on Windows, but you can define different default hotkeys based on the user's platform: [see here](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeskeybindings)

This is probably just an oversight, but in case it's intentional, here are some points to consider: 

- Out of all my extensions and keybindings, this is the only one that makes use of the Windows button, and binding to the Windows button is unconventional.
- Likely to break because Microsoft likes to create new Windows button hotkeys all the time (like `win+;` and `win+.` for the native emoji picker they added recently)',
- As a side effect of no one using Windows hotkeys, it's feels really uncomfortable for me to press the Windows button as a modifier while programming regularly.

**Comment by jeremychone** [comment]
@evaera yes, that's was an oversight, and I should fix it.

**Comment by jeremychone** [comment]
@evaera should be fixed in 0.3.1. Let me know if it is ok.

**Comment by SSmale** [comment]
`ctrl + '` is the default binding on windows to launch the integrated terminal. on install the extension has `ctrl + #` as the binding.
